package main.java.models.coordinate.positions;

public enum CoordinateZone {
    UPPER_LEFT_CORNER,
    RIGHT_UPPER_CORNER,
    LOWER_RIGHT_CORNER,
    LOWER_LEFT_CORNER,
    RIGHT_VERTICAL_BAND,
    LEFT_VERTICAL_BAND,
    HORIZONTAL_LOWER_BAND,
    HORIZONTAL_UPPER_BAND,
    CENTRAL_POSITION;
}

